// <auto-generated />
using System;
using M_Chat.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M_Chat.Services.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200629032619_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M_Chat.Models.Centro_educativo", b =>
                {
                    b.Property<string>("ClaveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel_Educativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaveId");

                    b.ToTable("Centro_Educativos");
                });

            modelBuilder.Entity("M_Chat.Models.Cuestionario", b =>
                {
                    b.Property<int>("Id_Cuestionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_aplicacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Cuestionario");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("M_Chat.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id_Diagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfanteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RespuestaId")
                        .HasColumnType("int");

                    b.Property<int?>("RespuestasId_Respuesta")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Diagnostico");

                    b.HasIndex("InfanteId");

                    b.HasIndex("RespuestasId_Respuesta");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("M_Chat.Models.Infante", b =>
                {
                    b.Property<string>("CurpId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Centro_educativoClaveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Nacimiento_Infante")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CurpId");

                    b.HasIndex("Centro_educativoClaveId");

                    b.HasIndex("TutorId");

                    b.ToTable("Infantes");
                });

            modelBuilder.Entity("M_Chat.Models.Preguntas", b =>
                {
                    b.Property<int>("Id_Pregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Pregunta");

                    b.HasIndex("CuestionarioId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("M_Chat.Models.Respuestas", b =>
                {
                    b.Property<int>("Id_Respuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PreguntaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreguntasId_Pregunta")
                        .HasColumnType("int");

                    b.Property<bool>("Respuesta")
                        .HasColumnType("bit");

                    b.Property<string>("TutorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_Respuesta");

                    b.HasIndex("PreguntasId_Pregunta");

                    b.HasIndex("TutorId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("M_Chat.Models.Tutor", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailId");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("M_Chat.Models.Diagnostico", b =>
                {
                    b.HasOne("M_Chat.Models.Infante", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("InfanteId");

                    b.HasOne("M_Chat.Models.Respuestas", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("RespuestasId_Respuesta");
                });

            modelBuilder.Entity("M_Chat.Models.Infante", b =>
                {
                    b.HasOne("M_Chat.Models.Centro_educativo", null)
                        .WithMany("Infantes")
                        .HasForeignKey("Centro_educativoClaveId");

                    b.HasOne("M_Chat.Models.Tutor", null)
                        .WithMany("Infantes")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("M_Chat.Models.Preguntas", b =>
                {
                    b.HasOne("M_Chat.Models.Cuestionario", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M_Chat.Models.Respuestas", b =>
                {
                    b.HasOne("M_Chat.Models.Preguntas", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntasId_Pregunta");

                    b.HasOne("M_Chat.Models.Tutor", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("TutorId");
                });
#pragma warning restore 612, 618
        }
    }
}
